name: chat_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^4.1.0
  firebase_auth: ^6.0.2
  modal_progress_hud_nsn: ^0.5.1
  cloud_firestore: ^6.0.1
  chat_bubbles: ^1.7.0
  flutter_native_splash: ^2.4.6
  flutter_bloc: ^9.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0   
  

flutter_native_splash:
  color: "#2F032F" 
  image: "assets/images/xelilovApp.png"

  android_12:
    image: "assets/images/xelilovApp.png"
    color: "#2F032F"

  android: true
  ios: true
  web: true

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Pacifico
      fonts:
        - asset: assets/fonts/Pacifico-Regular.ttf
