// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCl7vcarL3G67LcqzRGawVZuSOYVBHE4UI',
    appId: '1:486579411500:web:eecd20cbba53107aa24f89',
    messagingSenderId: '486579411500',
    projectId: 'chat-app-586d1',
    authDomain: 'chat-app-586d1.firebaseapp.com',
    storageBucket: 'chat-app-586d1.firebasestorage.app',
    measurementId: 'G-CTZ361WLJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBSa8mjJOMemLuwQEhYMA0p8_DJfnI9qpI',
    appId: '1:486579411500:android:d4b65328bc7a740aa24f89',
    messagingSenderId: '486579411500',
    projectId: 'chat-app-586d1',
    storageBucket: 'chat-app-586d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDOQ8L6hYCA3SZB0iYgT6lIoC7epCFL5EY',
    appId: '1:486579411500:ios:c1032548f523d0c1a24f89',
    messagingSenderId: '486579411500',
    projectId: 'chat-app-586d1',
    storageBucket: 'chat-app-586d1.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDOQ8L6hYCA3SZB0iYgT6lIoC7epCFL5EY',
    appId: '1:486579411500:ios:c1032548f523d0c1a24f89',
    messagingSenderId: '486579411500',
    projectId: 'chat-app-586d1',
    storageBucket: 'chat-app-586d1.firebasestorage.app',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCl7vcarL3G67LcqzRGawVZuSOYVBHE4UI',
    appId: '1:486579411500:web:2b382714d1b58ceaa24f89',
    messagingSenderId: '486579411500',
    projectId: 'chat-app-586d1',
    authDomain: 'chat-app-586d1.firebaseapp.com',
    storageBucket: 'chat-app-586d1.firebasestorage.app',
    measurementId: 'G-MXP1VT6LNB',
  );
}
